# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            JPBerriz
tagline:          'JPBerriz'
description:      'Life is Art'
url:              http://127.0.0.1:4000
baseurl:          

author:           
  name:           'Juan Pablo Berrizbeitia'
  url:            http://jpberriz.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jpberriz/jpberriz.net

include:          ['_pages']

# Site search 
tipue_search:
  include:
    pages:        true

# Google Analytics
google_analytics: G-P8VDRWRQ8P

plugins:
   - jekyll-admin
   - jekyll-paginate
   
